-- Daily audio storage: a PRIVATE bucket + read-only access for logged-in members.
--
-- The bucket is private (public = false) on purpose: a public bucket serves files
-- to anyone with the URL and bypasses access control. Members read via short-lived
-- signed URLs (createSignedUrl) generated by the app at play time; the SELECT policy
-- below is what authorizes that signing for an authenticated user.
--
-- There are deliberately NO insert/update/delete policies for `authenticated`, so
-- members cannot upload or alter audio. Files are loaded by the service role
-- (admin/seed), which bypasses RLS. SELECT syntax confirmed against the Supabase
-- storage access-control docs (2026-05): `to authenticated` + bucket_id in `using`.

insert into storage.buckets (id, name, public)
values ('daily-audio', 'daily-audio', false)
on conflict (id) do nothing;

create policy "members can read daily-audio"
  on storage.objects
  for select
  to authenticated
  using ( bucket_id = 'daily-audio' );
